### ISSUE TITLE
Can´t clone repossitory 

### ISSUE THREAD

**Issue by eduardomarco** [IBM/ibmi-oss-examples#158]
**Describe the bug**
I can´t clone
**To Reproduce**
PS D:\Users> cd .\workspace\
PS D:\Users\workspace> git clone git@github.com:IBM/ibmi-oss-examples.git
Cloning into 'ibmi-oss-examples'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
**Expected behavior**
clone the reposssitory
**Screenshots**

**Additional context**
Windows 10
C:\Users\eduar\AppData\Roaming\npm-cache\_logs>node -v
v14.17.1

**Comment by kadler** [comment]
In order to clone the repo with SSH, you'll need to have SSH keys set up on your client: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Alternatively, you can use HTTPS without setting anything up for SSH: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository
